In [27]:
# jupyter data science boilerplate
import numpy as np
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt

In [28]:
ts = pd.read_csv('./black_box_sku_vol.csv', sep = '\t', parse_dates = ['start_date'])
import datetime

ts['y']=[y[1:-1].split(",") for y in ts.y]
ts.y=ts.y.apply(lambda x:list(map(float,x)))

ts.head()

,sku_id,dc_id,start_date,y,flag
0,100000113335,3,2018-08-20,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",bulky_dc
1,100000115712,772,2018-12-22,"[2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",smallmid
2,100000245813,316,2019-03-05,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",smallmid
3,100000339301,5,2018-10-01,"[5.0, 0.0, 5.0, 3.0, 4.0, 2.0, 3.0, 0.0, 12.0,...",smallmid
4,100000376384,6,2018-09-25,"[22.0, 1.0, 1.0, 3.0, 8.0, 0.0, 31.0, 4.0, 10....",smallmid

In [29]:
ts['y']

0       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
1       [2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
2       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
3       [5.0, 0.0, 5.0, 3.0, 4.0, 2.0, 3.0, 0.0, 12.0,...
4       [22.0, 1.0, 1.0, 3.0, 8.0, 0.0, 31.0, 4.0, 10....
5       [1.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, ...
6       [1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 14.0, 3.0, 0.0,...
7       [2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
8       [22.0, 19.0, 17.0, 9.0, 10.0, 5.0, 11.0, 13.0,...
9       [1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 3.0, 0.0, 0.0, ...
10      [2.0, 0.0, 2.0, 2.0, 2.0, 2.0, 0.0, 0.0, 0.0, ...
11      [0.0, 0.0, 0.0, 0.0, 0.0, 20.0, 0.0, 0.0, 0.0,...
12      [40.0, 41.0, 45.0, 41.0, 54.0, 135.0, 21.0, 61...
13      [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
14      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
15      [135.0, 13.0, 3.0, 5.0, 35.0, 77.0, 31.0, 33.0...
16      [1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.0, 1.0, ...
17      [2.0, 0.0, 1.0, 1.0, 1.0, 3.0, 3.0, 1.0, 0.0, ...
18      [4.0, 3.0, 1.0, 2.0, 0.0, 1.0, 6.0, 4.0, 8.0, ...
19      [2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, ...
20      [2.0, 2.0, 3.0, 5.0, 4.0, 0.0, 4.0, 5.0, 9.0, ...
21      [1.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, ...
22      [1.0, 1.0, 0.0, 0.0, 1.0, 2.0, 0.0, 2.0, 1.0, ...
23      [2.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, ...
24      [2.0, 22.0, 19.0, 30.0, 40.0, 60.0, 36.0, 47.0...
25      [1.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...
26      [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
27      [2.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...
28      [3.0, 0.0, 0.0, 25.0, 2.0, 0.0, 0.0, 0.0, 1.0,...
29      [10.0, 12.0, 15.0, 13.0, 13.0, 26.0, 21.0, 24....
                              ...
7414    [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7415    [3.0, 0.0, 5.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...
7416    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7417    [128.0, 129.0, 99.0, 88.0, 100.0, 109.0, 94.0,...
7418    [4.0, 5.0, 2.0, 2.0, 7.0, 117.0, 13.0, 7.0, 22...
7419    [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, ...
7420    [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...
7421    [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7422    [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 9.0, ...
7423    [35.0, 19.0, 3.0, 4.0, 5.0, 21.0, 3.0, 27.0, 1...
7424    [2.0, 7.0, 2.0, 2.0, 2.0, 2.0, 2.0, 4.0, 0.0, ...
7425    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7426    [3.0, 2.0, 0.0, 0.0, 1.0, 1.0, 2.0, 1.0, 0.0, ...
7427    [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7428    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7429    [2.0, 6.0, 4.0, 2.0, 2.0, 0.0, 4.0, 1.0, 2.0, ...
7430    [13.0, 45.0, 61.0, 106.0, 112.0, 59.0, 44.0, 8...
7431    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7432    [9.0, 1.0, 0.0, 0.0, 5.0, 9.0, 0.0, 0.0, 1.0, ...
7433    [2.0, 3.0, 3.0, 4.0, 11.0, 3.0, 6.0, 5.0, 2.0,...
7434    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7435    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7436    [2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7437    [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...
7438    [1.0, 3.0, 1.0, 0.0, 11.0, 6.0, 10.0, 3.0, 7.0...
7439    [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...
7440    [2.0, 1.0, 1.0, 3.0, 2.0, 1.0, 8.0, 0.0, 0.0, ...
7441    [7.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...
7442    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7443    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
Name: y, Length: 7444, dtype: object

In [30]:
ts['training'] = ts.y.apply(lambda x:x[-8-30:])

In [31]:
a = ts.loc[ts['training'].apply(lambda x:len(x))==(30+8),:]

In [32]:
a['training'] = a.training.apply(lambda x:x[-8-30:-8])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
a['predicted'] = a.training.apply(lambda x:x[-7:])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
len(a)

7389

In [35]:
a.head()

,sku_id,dc_id,start_date,y,flag,training,predicted
0,100000113335,3,2018-08-20,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",bulky_dc,"[0.0, 0.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 0.0, ...","[5.0, 3.0, 0.0, 0.0, 23.0, 0.0, 0.0]"
1,100000115712,772,2018-12-22,"[2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",smallmid,"[0.0, 0.0, 5.0, 1.0, 2.0, 0.0, 5.0, 0.0, 1.0, ...","[3.0, 0.0, 0.0, 1.0, 5.0, 0.0, 8.0]"
3,100000339301,5,2018-10-01,"[5.0, 0.0, 5.0, 3.0, 4.0, 2.0, 3.0, 0.0, 12.0,...",smallmid,"[1.0, 1.0, 3.0, 12.0, 0.0, 2.0, 6.0, 0.0, 4.0,...","[1.0, 0.0, 1.0, 1.0, 21.0, 4.0, 4.0]"
4,100000376384,6,2018-09-25,"[22.0, 1.0, 1.0, 3.0, 8.0, 0.0, 31.0, 4.0, 10....",smallmid,"[3.0, 1.0, 9.0, 17.0, 6.0, 0.0, 19.0, 1.0, 0.0...","[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]"
5,100000472682,3,2019-01-26,"[1.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, ...",smallmid,"[2.0, 2.0, 1.0, 1.0, 0.0, 2.0, 14.0, 2.0, 2.0,...","[0.0, 4.0, 3.0, 0.0, 1.0, 9.0, 3.0]"

In [36]:
train_data = np.array(a['training'].values.tolist())

print(type(train_data[0]))

print(train_data.shape)

<class 'numpy.ndarray'>
(7389, 30)

In [37]:
import simdkalman

# define a Kalman filter model with a weekly cycle, parametrized by a simple "smoothing factor", s
smoothing_factor = 5.0

n_seasons = 7

# --- define state transition matrix A
state_transition = np.zeros((n_seasons+1, n_seasons+1))
# hidden level
state_transition[0,0] = 1
# season cycle
state_transition[1,1:-1] = [-1.0] * (n_seasons-1)
state_transition[2:,1:-1] = np.eye(n_seasons-1)

# --- observation model H
# observation is hidden level + weekly seasonal compoenent
observation_model = [[1,1] + [0]*(n_seasons-1)]

# --- noise models, parametrized by the smoothing factor
level_noise = 0.2 / smoothing_factor
observation_noise = 0.2
season_noise = 1e-3

process_noise_cov = np.diag([level_noise, season_noise] + [0]*(n_seasons-1))**2
observation_noise_cov = observation_noise**2

kf = simdkalman.KalmanFilter(
    state_transition,
    process_noise_cov,
    observation_model,
    observation_noise_cov)

In [38]:
block = train_data
n_train = block.shape[1]
n_test = 7
result = kf.compute(block, n_test)

In [39]:
# ground-truth 
print(a['predicted'][17])
print(result.predicted.observations.mean[0])

[205.0, 275.0, 231.0, 168.0, 1121.0, 134.0, 237.0]
[ 2.99079086  1.66179676  1.08251914  0.75281753 12.92021189  1.5191633
  5.65533818]

In [40]:
print(len(result.predicted.observations.mean))

7389

In [41]:
len(a)

7389

In [42]:
a['kf_sum']=[ sum(i) for i in result.predicted.observations.mean]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [43]:
a['ground_sum']=[ sum(i) for i in a['predicted']]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [44]:
a

,sku_id,dc_id,start_date,y,flag,training,predicted,kf_sum,ground_sum
0,100000113335,3,2018-08-20,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",bulky_dc,"[0.0, 0.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 0.0, ...","[5.0, 3.0, 0.0, 0.0, 23.0, 0.0, 0.0]",26.582638,31.0
1,100000115712,772,2018-12-22,"[2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",smallmid,"[0.0, 0.0, 5.0, 1.0, 2.0, 0.0, 5.0, 0.0, 1.0, ...","[3.0, 0.0, 0.0, 1.0, 5.0, 0.0, 8.0]",18.228189,17.0
3,100000339301,5,2018-10-01,"[5.0, 0.0, 5.0, 3.0, 4.0, 2.0, 3.0, 0.0, 12.0,...",smallmid,"[1.0, 1.0, 3.0, 12.0, 0.0, 2.0, 6.0, 0.0, 4.0,...","[1.0, 0.0, 1.0, 1.0, 21.0, 4.0, 4.0]",38.475739,32.0
4,100000376384,6,2018-09-25,"[22.0, 1.0, 1.0, 3.0, 8.0, 0.0, 31.0, 4.0, 10....",smallmid,"[3.0, 1.0, 9.0, 17.0, 6.0, 0.0, 19.0, 1.0, 0.0...","[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]",3.282873,1.0
5,100000472682,3,2019-01-26,"[1.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, ...",smallmid,"[2.0, 2.0, 1.0, 1.0, 0.0, 2.0, 14.0, 2.0, 2.0,...","[0.0, 4.0, 3.0, 0.0, 1.0, 9.0, 3.0]",22.057484,20.0
6,100000541139,10,2018-12-14,"[1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 14.0, 3.0, 0.0,...",smallmid,"[0.0, 8.0, 10.0, 3.0, 7.0, 9.0, 7.0, 1.0, 23.0...","[4.0, 2.0, 0.0, 0.0, 13.0, 1.0, 9.0]",31.465350,29.0
7,100000541205,5,2019-01-02,"[2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",smallmid,"[0.0, 0.0, 0.0, 0.0, 0.0, 5.0, 0.0, 1.0, 1.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.282401,0.0
8,100000822981,3,2018-10-17,"[22.0, 19.0, 17.0, 9.0, 10.0, 5.0, 11.0, 13.0,...",smallmid,"[190.0, 162.0, 157.0, 155.0, 136.0, 103.0, 168...","[77.0, 79.0, 72.0, 76.0, 69.0, 69.0, 80.0]",524.520008,522.0
9,100000979055,3,2018-11-16,"[1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 3.0, 0.0, 0.0, ...",smallmid,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,0.0
10,100001037832,6,2018-11-20,"[2.0, 0.0, 2.0, 2.0, 2.0, 2.0, 0.0, 0.0, 0.0, ...",smallmid,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,0.0
11,100001393357,772,2018-11-28,"[0.0, 0.0, 0.0, 0.0, 0.0, 20.0, 0.0, 0.0, 0.0,...",smallmid,"[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1.0, 15.0, 0.0, 1.0, 7.0, 0.0, 0.0]",19.697705,24.0
12,100001786468,10,2019-01-28,"[40.0, 41.0, 45.0, 41.0, 54.0, 135.0, 21.0, 61...",smallmid,"[0.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 10.0, 24.0]",37.680583,34.0
13,100001838072,5,2018-12-03,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",smallmid,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0]",2.107995,2.0
14,100002285194,6,2019-01-04,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",smallmid,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,0.0
15,100002293114,5,2018-12-12,"[135.0, 13.0, 3.0, 5.0, 35.0, 77.0, 31.0, 33.0...",smallmid,"[4.0, 4.0, 25.0, 19.0, 107.0, 73.0, 33.0, 97.0...","[69.0, 85.0, 56.0, 72.0, 54.0, 44.0, 35.0]",411.462812,415.0
16,100002689508,772,2019-01-16,"[1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.0, 1.0, ...",smallmid,"[0.0, 2.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, ...","[5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",4.065118,5.0
17,1003066,9,2014-03-06,"[2.0, 0.0, 1.0, 1.0, 1.0, 3.0, 3.0, 1.0, 0.0, ...",smallmid,"[394.0, 266.0, 296.0, 203.0, 228.0, 218.0, 228...","[205.0, 275.0, 231.0, 168.0, 1121.0, 134.0, 23...",2326.125763,2371.0
18,1031411,4,2014-03-04,"[4.0, 3.0, 1.0, 2.0, 0.0, 1.0, 6.0, 4.0, 8.0, ...",smallmid,"[13.0, 13.0, 20.0, 15.0, 12.0, 15.0, 38.0, 14....","[21.0, 32.0, 17.0, 9.0, 22.0, 10.0, 16.0]",132.341421,127.0
19,1071557,9,2014-06-02,"[2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, ...",smallmid,"[3.0, 1.0, 0.0, 1.0, 4.0, 3.0, 1.0, 10.0, 5.0,...","[0.0, 3.0, 3.0, 0.0, 2.0, 0.0, 3.0]",13.316130,11.0
20,1076553,3,2014-03-17,"[2.0, 2.0, 3.0, 5.0, 4.0, 0.0, 4.0, 5.0, 9.0, ...",smallmid,"[29.0, 25.0, 10.0, 12.0, 13.0, 7.0, 36.0, 29.0...","[7.0, 13.0, 4.0, 3.0, 34.0, 7.0, 17.0]",87.670327,85.0
21,1078104,9,2014-04-01,"[1.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, ...",smallmid,"[36.0, 56.0, 37.0, 54.0, 49.0, 50.0, 40.0, 29....","[47.0, 61.0, 57.0, 43.0, 54.0, 50.0, 53.0]",352.019848,365.0
22,1078130,5,2014-04-02,"[1.0, 1.0, 0.0, 0.0, 1.0, 2.0, 0.0, 2.0, 1.0, ...",smallmid,"[28.0, 20.0, 38.0, 39.0, 28.0, 19.0, 17.0, 12....","[13.0, 52.0, 27.0, 12.0, 17.0, 31.0, 37.0]",185.684410,189.0
23,1078168,9,2014-04-21,"[2.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, ...",smallmid,"[62.0, 54.0, 44.0, 43.0, 52.0, 54.0, 59.0, 44....","[36.0, 54.0, 26.0, 31.0, 53.0, 36.0, 47.0]",289.362552,283.0
24,1236046,6,2014-10-04,"[2.0, 22.0, 19.0, 30.0, 40.0, 60.0, 36.0, 47.0...",smallmid,"[79.0, 88.0, 54.0, 94.0, 89.0, 49.0, 105.0, 84...","[191.0, 109.0, 120.0, 73.0, 162.0, 58.0, 71.0]",754.575430,784.0
25,1253192,5,2015-03-07,"[1.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...",bulky_dc,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,0.0
26,1342156,316,2015-03-05,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",smallmid,"[11.0, 0.0, 4.0, 6.0, 8.0, 0.0, 1.0, 3.0, 0.0,...","[5.0, 6.0, 5.0, 7.0, 5.0, 3.0, 5.0]",32.948348,36.0
27,1686544,772,2015-09-28,"[2.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...",smallmid,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0]",3.160151,3.0
28,1993091,5,2015-11-08,"[3.0, 0.0, 0.0, 25.0, 2.0, 0.0, 0.0, 0.0, 1.0,...",bulky_dc,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,0.0
29,2146352,6,2016-01-26,"[10.0, 12.0, 15.0, 13.0, 13.0, 26.0, 21.0, 24....",smallmid,"[255.0, 364.0, 184.0, 152.0, 169.0, 160.0, 206...","[137.0, 229.0, 141.0, 190.0, 119.0, 110.0, 128.0]",999.383125,1054.0
30,2154045,3,2015-11-24,"[3.0, 5.0, 4.0, 2.0, 2.0, 11.0, 12.0, 8.0, 12....",smallmid,"[38.0, 26.0, 32.0, 48.0, 46.0, 37.0, 203.0, 17...","[173.0, 79.0, 60.0, 66.0, 65.0, 40.0, 36.0]",477.632875,519.0
...,...,...,...,...,...,...,...,...,...
7414,4903500,4,2017-05-08,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",bulky_dc,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, ...","[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]",1.860485,2.0
7415,5056253,6,2017-09-19,"[3.0, 0.0, 5.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...",smallmid,"[7.0, 0.0, 0.0, 0.0, 2.0, 1.0, 0.0, 4.0, 1.0, ...","[0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0]",2.296429,3.0
7416,5093389,5,2018-01-26,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",bulky_dc,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,0.0
7417,526830,5,2014-01-01,"[128.0, 129.0, 99.0, 88.0, 100.0, 109.0, 94.0,...",smallmid,"[480.0, 402.0, 200.0, 240.0, 192.0, 2420.0, 84...","[1581.0, 2265.0, 1923.0, 370.0, 238.0, 149.0, ...",4456.453333,6727.0
7418,5273645,3,2017-12-07,"[4.0, 5.0, 2.0, 2.0, 7.0, 117.0, 13.0, 7.0, 22...",smallmid,"[514.0, 312.0, 420.0, 227.0, 510.0, 257.0, 299...","[465.0, 198.0, 241.0, 159.0, 370.0, 357.0, 192.0]",1948.823158,1982.0
7419,528481,316,2014-01-01,"[1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, ...",smallmid,"[15.0, 11.0, 16.0, 15.0, 14.0, 15.0, 16.0, 7.0...","[30.0, 21.0, 11.0, 18.0, 9.0, 18.0, 11.0]",114.918488,118.0
7420,5286451,9,2017-10-20,"[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...",smallmid,"[1.0, 2.0, 0.0, 1.0, 0.0, 0.0, 0.0, 5.0, 1.0, ...","[3.0, 1.0, 1.0, 0.0, 1.0, 0.0, 2.0]",7.990648,8.0
7421,5394398,10,2017-09-02,"[1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",bulky_dc,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",-0.027013,0.0
7422,5509350,6,2017-11-03,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 9.0, ...",bulky_dc,"[3.0, 3.0, 0.0, 2.0, 3.0, 1.0, 5.0, 1.0, 2.0, ...","[13.0, 1.0, 5.0, 2.0, 2.0, 1.0, 0.0]",18.073548,24.0
7423,5663444,4,2017-11-15,"[35.0, 19.0, 3.0, 4.0, 5.0, 21.0, 3.0, 27.0, 1...",smallmid,"[138.0, 153.0, 114.0, 91.0, 54.0, 53.0, 223.0,...","[166.0, 91.0, 49.0, 32.0, 191.0, 152.0, 148.0]",829.287491,829.0
7424,5911577,9,2018-01-05,"[2.0, 7.0, 2.0, 2.0, 2.0, 2.0, 2.0, 4.0, 0.0, ...",smallmid,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[5.0, 2.0, 2.0, 3.0, 1.0, 1.0, 8.0]",25.181437,22.0
7425,6051314,6,2018-01-01,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",bulky_dc,"[24.0, 9.0, 32.0, 12.0, 23.0, 0.0, 49.0, 15.0,...","[38.0, 42.0, 13.0, 0.0, 40.0, 10.0, 8.0]",132.395266,151.0
7426,626738,5,2014-01-03,"[3.0, 2.0, 0.0, 0.0, 1.0, 1.0, 2.0, 1.0, 0.0, ...",smallmid,"[9.0, 20.0, 14.0, 8.0, 8.0, 28.0, 56.0, 20.0, ...","[65.0, 32.0, 68.0, 14.0, 19.0, 14.0, 14.0]",166.915944,226.0
7427,6559513,3,2018-03-28,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",smallmid,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.0]",2.418798,4.0
7428,6601403,772,2018-03-26,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",bulky_dc,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,0.0
7429,6659466,5,2018-03-26,"[2.0, 6.0, 4.0, 2.0, 2.0, 0.0, 4.0, 1.0, 2.0, ...",smallmid,"[23.0, 37.0, 19.0, 27.0, 19.0, 18.0, 34.0, 14....","[13.0, 16.0, 14.0, 8.0, 7.0, 11.0, 13.0]",86.280554,82.0
7430,7191176,3,2018-04-29,"[13.0, 45.0, 61.0, 106.0, 112.0, 59.0, 44.0, 8...",smallmid,"[151.0, 120.0, 200.0, 180.0, 107.0, 401.0, 861...","[258.0, 93.0, 148.0, 97.0, 188.0, 164.0, 123.0]",1180.657327,1071.0
7431,7298201,10,2018-04-23,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",bulky_dc,"[4.0, 0.0, 6.0, 1.0, 3.0, 2.0, 1.0, 2.0, 0.0, ...","[7.0, 2.0, 4.0, 1.0, 2.0, 2.0, 0.0]",16.986260,18.0
7432,7376326,4,2018-08-10,"[9.0, 1.0, 0.0, 0.0, 5.0, 9.0, 0.0, 0.0, 1.0, ...",smallmid,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,0.0
7433,7441911,6,2018-05-08,"[2.0, 3.0, 3.0, 4.0, 11.0, 3.0, 6.0, 5.0, 2.0,...",smallmid,"[2.0, 4.0, 3.0, 13.0, 9.0, 16.0, 6.0, 3.0, 9.0...","[6.0, 11.0, 9.0, 3.0, 6.0, 9.0, 5.0]",46.930851,49.0
7434,7566239,3,2018-06-04,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",bulky_dc,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[8.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0]",7.187325,10.0
7435,8172232,10,2018-07-19,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",bulky_dc,"[1.0, 0.0, 2.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, ...","[2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]",3.560760,4.0
7436,8261887,10,2018-08-07,"[2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",smallmid,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.409325,0.0
7437,8300836,9,2018-08-10,"[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...",smallmid,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 12.0, 9.0,...","[6.0, 6.0, 8.0, 6.0, 5.0, 6.0, 9.0]",51.231234,46.0
7438,830486,3,2014-01-01,"[1.0, 3.0, 1.0, 0.0, 11.0, 6.0, 10.0, 3.0, 7.0...",smallmid,"[61.0, 142.0, 804.0, 120.0, 135.0, 137.0, 75.0...","[4903.0, 2805.0, 166.0, 161.0, 118.0, 168.0, 4...",12581.447499,13192.0
7439,830489,5,2014-01-06,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...",smallmid,"[40.0, 43.0, 20.0, 36.0, 48.0, 40.0, 19.0, 21....","[68.0, 115.0, 40.0, 33.0, 29.0, 66.0, 70.0]",391.100120,421.0
7440,8313186,772,2018-08-02,"[2.0, 1.0, 1.0, 3.0, 2.0, 1.0, 8.0, 0.0, 0.0, ...",smallmid,"[1.0, 3.0, 3.0, 2.0, 3.0, 1.0, 6.0, 4.0, 3.0, ...","[4.0, 0.0, 1.0, 4.0, 4.0, 1.0, 3.0]",19.658901,17.0
7441,8647137,4,2018-08-27,"[7.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...",smallmid,"[35.0, 10.0, 23.0, 5.0, 28.0, 13.0, 17.0, 23.0...","[19.0, 13.0, 5.0, 21.0, 5.0, 11.0, 14.0]",91.760417,88.0
7442,8790547,5,2018-08-13,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",bulky_dc,"[1.0, 1.0, 11.0, 10.0, 0.0, 1.0, 0.0, 1.0, 10....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",1.173343,0.0
7443,8812627,4,2018-08-16,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",bulky_dc,"[1.0, 1.0, 4.0, 0.0, 1.0, 0.0, 2.0, 2.0, 1.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",-5.376171,0.0

In [45]:
a[['kf_sum','ground_sum']].to_csv('kf_30_black_box.csv')

In [65]:
pd.read_csv('kf_365.csv').head()

   Unnamed: 0      kf_sum  ground_sum
0         100  149.281348       105.0
1         101   74.899634        64.0
2         102   56.392053        54.0
3         103   13.541692        40.0
4         104  160.858886       160.0